### ISSUE TITLE
Dockerfile commands highlighted are not case-sensitive

### ISSUE THREAD

**Issue by hayderimran7** [ekalinin/Dockerfile.vim#17]
I installed the plugin but very soon I figured out that the highlighting is messing with my dockerfile.
for instance, i had to run a script called `run.sh` , now the plugin is supposedly highlight RUN command,
since its a dockerfile but it also highlighted my script name i.e. run.sh "run" was highlighted .
like following:
```
COPY run.sh /usr/local/bin/run.sh
```
*run* was seen highlighted. If you guys can make the highlighting as case sensitive, will really appreciate it :)

**Comment by ekalinin** [comment]
Thanks for report. Fixed.

**Comment by hayderimran7** [comment]
Thank you. Works good now :)
