### ISSUE TITLE
Remove non-Dockerfile keywords?

### ISSUE THREAD

**Issue by frewsxcv** [ekalinin/Dockerfile.vim#32]
https://github.com/ekalinin/Dockerfile.vim/blob/8401e017bb2c7987f306eb5a92c80016c915422e/syntax/Dockerfile.vim#L22-L28

Why do these commands get special treatment?

**Comment by ekalinin** [comment]
Hey @frewsxcv 

It's just most used commands from bash.
For convenience I decided to add the highlighting for them.

**Comment by ekalinin** [comment]
They disturb you somehow?

**Comment by frewsxcv** [comment]
Doesn't bother me that much, it just causes words to be highlighted in my code that shouldn't be highlighted:

![screen shot 2016-01-26 at 7 43 37 am](https://cloud.githubusercontent.com/assets/416575/12580829/a8c41ebe-c400-11e5-8bc5-182ca7ee237a.png)

**Comment by frewsxcv** [comment]
Feel free to close this though
