### ISSUE TITLE
when pasting into a Dockerfile comment lines trigger everything to get commented out

### ISSUE THREAD

**Issue by scottstensland** [ekalinin/Dockerfile.vim#34]
Great token coloring however when pasting from clipboard into a vim session if the text getting pasted contains comments then incorrectly all subsequent lines of text get commented out

Example :  

text copied from one Dockerfile :  

`

```
RUN apt-get update

# install nodejs and npm
RUN apt-get install -y nodejs npm git git-core


ADD index.js /tmp/
ADD package.json /tmp/
ADD start.sh /tmp/
```

`

then pasted into a Dockerfile   get transformed into : 

`

```
RUN apt-get update

# install nodejs and npm
# RUN apt-get install -y nodejs npm git git-core
#
#
# ADD index.js /tmp/
# ADD package.json /tmp/
# ADD start.sh /tmp/
#
```

`

**Comment by ekalinin** [comment]
Hey @scottstensland 

Did you try [paste mode](http://vim.wikia.com/wiki/Toggle_auto-indenting_for_code_paste)?
