### ISSUE TITLE
dockerfile.vim should recognize Dockerfile.multi 

### ISSUE THREAD

**Issue by webermaster** [ekalinin/Dockerfile.vim#51]
Currently Dockerfile.vim seems to only recognize files by the name of "Dockerfile".  From what I've seena common naming convention for multistage builds is "Dockerfile.multi".  Should Dockerfile.vim recognize this filename for syntax highlighting as well?

  
<img width="381" alt="screen shot 2018-01-03 at 8 09 21 am" src="https://user-images.githubusercontent.com/9516168/34523523-7dc85da2-f05d-11e7-9f68-4723e32e5b1b.png">

**Comment by belak** [comment]
I'm not sure this is true - https://github.com/ekalinin/Dockerfile.vim/blob/master/ftdetect/Dockerfile.vim#L3

That seems to match any file that starts with `Dockerfile`.

Are you still having this issue? When I tried to reproduce this it seemed to work without any issues.

**Comment by bgaillard** [comment]
Hi, in my case I can open a file named `Dockerfile.android` and coloration works as expected. So IMO this issue can be closed. @webermaster do you agree ?

**Comment by niklaas** [comment]
Hm. Having trouble with syntax highlighting for `Dockerfile` (without `.multi`) as well. Using `vim-polyglot` I see no highlighting. That said, disabling it with `let g:polyglot_disabled = ['dockerfile']` and loading `ekalinin/Dockerfile.vim` manually works.

**Comment by ekalinin** [comment]
@webermaster please, try the latest version of the Dockerfile.vim

Just tried:

```
➜ vim Dockerfile.multi
```

and file type was set correctly.
