### ISSUE TITLE
When installing with vundle, the syntax highlighter is not picked up

### ISSUE THREAD

**Issue by philippeback** [ekalinin/Dockerfile.vim#54]
To solve I had to install the plugin normally.
But then I had to go into where the plugin got installed

![selection_656](https://user-images.githubusercontent.com/2128441/41039366-82fc30b8-6999-11e8-833d-9accf7ef2ec0.png)

And perform 

    make install

from there.

It then all worked nicely, yay!

**Comment by ekalinin** [comment]
Thanks for report.
What OS and vim version did you use?

**Comment by philippeback** [comment]
This is

    VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:42:52)

Running on an `Ubuntu 14.04.5 LTS (trusty)` (old stuff in a VM with too much installed to move forward...)
