### ISSUE TITLE
detect lowercase dockerfile name

### ISSUE THREAD

**Issue by cdrani** [ekalinin/Dockerfile.vim#59]
Currently only detects capitalized file name:
```vim
autocmd BufRead,BufNewFile Dockerfile set ft=Dockerfile
autocmd BufRead,BufNewFile Dockerfile* set ft=Dockerfile
```
except for wildcards:
```vim
autocmd BufRead,BufNewFile *.dock set ft=Dockerfile
autocmd BufRead,BufNewFile *.[Dd]ockerfile set ft=Dockerfile
```
Is there a strict reason why it can't support lowercase filenames with no extensions? I am new to docker and curious about this.

**Comment by kwakwaversal** [comment]
Seems reasonable to accept both `Dockerfile` and `dockerfile`.

The creators of docker addressed this specifically https://github.com/moby/moby/issues/10807 which inspired https://github.com/moby/moby/pull/10858.

I've yet to come across the file extension `.dock` but that's not to say it's not a thing. I typically do `Dockerfile.foo` and `Dockerfile.bar`.
