### ISSUE TITLE
Dockerfile.Foo does not cause filetype to be set

### ISSUE THREAD

**Issue by ethagnawl** [ekalinin/Dockerfile.vim#63]
Would the maintainers consider a pull request which added the compliment to the existing trailing `*.[Dd]ockerfile` filetype setter?

Something like:
`autocmd BufRead,BufNewFile [Dd]ockerfile.* set ft=Dockerfile`

I'm not sure how common this convention is, but I have seen it used in a few projects I've worked on.

**Comment by ekalinin** [comment]
Hey,

We have this setting here:

https://github.com/ekalinin/Dockerfile.vim/blob/e15706106a5edd1120c23a593e560e51218c77bd/ftdetect/Dockerfile.vim#L5

Doesn't it work?

**Comment by ethagnawl** [comment]
Apologies. This was end user error.
